In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("dataset_Facebook.csv",sep=";")

In [3]:
df

,Page total likes,Type,Category,Post Month,Post Weekday,Post Hour,Paid,Lifetime Post Total Reach,Lifetime Post Total Impressions,Lifetime Engaged Users,Lifetime Post Consumers,Lifetime Post Consumptions,Lifetime Post Impressions by people who have liked your Page,Lifetime Post reach by people who like your Page,Lifetime People who have liked your Page and engaged with your post,comment,like,share,Total Interactions
0,139441,Photo,2,12,4,3,0.0,2752,5091,178,109,159,3078,1640,119,4,79.0,17.0,100
1,139441,Status,2,12,3,10,0.0,10460,19057,1457,1361,1674,11710,6112,1108,5,130.0,29.0,164
2,139441,Photo,3,12,3,3,0.0,2413,4373,177,113,154,2812,1503,132,0,66.0,14.0,80
3,139441,Photo,2,12,2,10,1.0,50128,87991,2211,790,1119,61027,32048,1386,58,1572.0,147.0,1777
4,139441,Photo,2,12,2,3,0.0,7244,13594,671,410,580,6228,3200,396,19,325.0,49.0,393
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,85093,Photo,3,1,7,2,0.0,4684,7536,733,708,985,4750,2876,392,5,53.0,26.0,84
496,81370,Photo,2,1,5,8,0.0,3480,6229,537,508,687,3961,2104,301,0,53.0,22.0,75
497,81370,Photo,1,1,5,2,0.0,3778,7216,625,572,795,4742,2388,363,4,93.0,18.0,115
498,81370,Photo,3,1,4,11,0.0,4156,7564,626,574,832,4534,2452,370,7,91.0,38.0,136
499,81370,Photo,2,1,4,4,NaN,4188,7292,564,524,743,3861,2200,316,0,91.0,28.0,119

In [4]:
df.columns

Index(['Page total likes', 'Type', 'Category', 'Post Month', 'Post Weekday',
       'Post Hour', 'Paid', 'Lifetime Post Total Reach',
       'Lifetime Post Total Impressions', 'Lifetime Engaged Users',
       'Lifetime Post Consumers', 'Lifetime Post Consumptions',
       'Lifetime Post Impressions by people who have liked your Page',
       'Lifetime Post reach by people who like your Page',
       'Lifetime People who have liked your Page and engaged with your post',
       'comment', 'like', 'share', 'Total Interactions'],
      dtype='object')

In [5]:
df.isnull().sum()

Page total likes                                                       0
Type                                                                   0
Category                                                               0
Post Month                                                             0
Post Weekday                                                           0
Post Hour                                                              0
Paid                                                                   1
Lifetime Post Total Reach                                              0
Lifetime Post Total Impressions                                        0
Lifetime Engaged Users                                                 0
Lifetime Post Consumers                                                0
Lifetime Post Consumptions                                             0
Lifetime Post Impressions by people who have liked your Page           0
Lifetime Post reach by people who like your Page                       0
Lifetime People who have liked your Page and engaged with your post    0
comment                                                                0
like                                                                   1
share                                                                  4
Total Interactions                                                     0
dtype: int64

In [6]:
df['Paid'] = df['Paid'].fillna(value=0.0)

In [7]:
df.isnull().sum()

Page total likes                                                       0
Type                                                                   0
Category                                                               0
Post Month                                                             0
Post Weekday                                                           0
Post Hour                                                              0
Paid                                                                   0
Lifetime Post Total Reach                                              0
Lifetime Post Total Impressions                                        0
Lifetime Engaged Users                                                 0
Lifetime Post Consumers                                                0
Lifetime Post Consumptions                                             0
Lifetime Post Impressions by people who have liked your Page           0
Lifetime Post reach by people who like your Page                       0
Lifetime People who have liked your Page and engaged with your post    0
comment                                                                0
like                                                                   1
share                                                                  4
Total Interactions                                                     0
dtype: int64

In [8]:
df['like'].fillna(df['like'].mean(), inplace=True)

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_51304\3295622645.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['like'].fillna(df['like'].mean(), inplace=True)

In [9]:
df.isnull().sum()

Page total likes                                                       0
Type                                                                   0
Category                                                               0
Post Month                                                             0
Post Weekday                                                           0
Post Hour                                                              0
Paid                                                                   0
Lifetime Post Total Reach                                              0
Lifetime Post Total Impressions                                        0
Lifetime Engaged Users                                                 0
Lifetime Post Consumers                                                0
Lifetime Post Consumptions                                             0
Lifetime Post Impressions by people who have liked your Page           0
Lifetime Post reach by people who like your Page                       0
Lifetime People who have liked your Page and engaged with your post    0
comment                                                                0
like                                                                   0
share                                                                  4
Total Interactions                                                     0
dtype: int64

In [10]:
shr_mean = df['share'].mean()
df['share'].fillna(shr_mean,inplace=True)

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_51304\1775284877.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['share'].fillna(shr_mean,inplace=True)

In [11]:
df.isnull().sum()

Page total likes                                                       0
Type                                                                   0
Category                                                               0
Post Month                                                             0
Post Weekday                                                           0
Post Hour                                                              0
Paid                                                                   0
Lifetime Post Total Reach                                              0
Lifetime Post Total Impressions                                        0
Lifetime Engaged Users                                                 0
Lifetime Post Consumers                                                0
Lifetime Post Consumptions                                             0
Lifetime Post Impressions by people who have liked your Page           0
Lifetime Post reach by people who like your Page                       0
Lifetime People who have liked your Page and engaged with your post    0
comment                                                                0
like                                                                   0
share                                                                  0
Total Interactions                                                     0
dtype: int64

In [14]:
sub1 = df[df['Type'] == 'Photo']
sub1.shape

(426, 19)

In [16]:
sub2 = df[df['Type'] == 'Status']
sub2.shape

(45, 19)

In [19]:
sub3 = df.iloc[:100]
sub3.shape

(100, 19)

In [21]:
sub4  = df.iloc[100:]
sub4.shape

(400, 19)

In [22]:
df.columns

Index(['Page total likes', 'Type', 'Category', 'Post Month', 'Post Weekday',
       'Post Hour', 'Paid', 'Lifetime Post Total Reach',
       'Lifetime Post Total Impressions', 'Lifetime Engaged Users',
       'Lifetime Post Consumers', 'Lifetime Post Consumptions',
       'Lifetime Post Impressions by people who have liked your Page',
       'Lifetime Post reach by people who like your Page',
       'Lifetime People who have liked your Page and engaged with your post',
       'comment', 'like', 'share', 'Total Interactions'],
      dtype='object')

In [24]:
sub5 = df[['Page total likes','Type','Category','Post Month','Post Weekday','Post Hour','Paid']]
sub5.shape

(500, 7)

In [26]:
sub6 = df[['Lifetime Post Total Impressions','Lifetime Engaged Users','Lifetime Post Consumers','Lifetime Post Consumptions']]
sub6.shape

(500, 4)

In [30]:
merge1 = pd.concat([sub1,sub2])
merge1

,Page total likes,Type,Category,Post Month,Post Weekday,Post Hour,Paid,Lifetime Post Total Reach,Lifetime Post Total Impressions,Lifetime Engaged Users,Lifetime Post Consumers,Lifetime Post Consumptions,Lifetime Post Impressions by people who have liked your Page,Lifetime Post reach by people who like your Page,Lifetime People who have liked your Page and engaged with your post,comment,like,share,Total Interactions
0,139441,Photo,2,12,4,3,0.0,2752,5091,178,109,159,3078,1640,119,4,79.0,17.0,100
2,139441,Photo,3,12,3,3,0.0,2413,4373,177,113,154,2812,1503,132,0,66.0,14.0,80
3,139441,Photo,2,12,2,10,1.0,50128,87991,2211,790,1119,61027,32048,1386,58,1572.0,147.0,1777
4,139441,Photo,2,12,2,3,0.0,7244,13594,671,410,580,6228,3200,396,19,325.0,49.0,393
6,139441,Photo,3,12,1,3,1.0,11692,19479,481,265,364,15432,9328,379,3,249.0,27.0,279
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
334,119198,Status,2,5,1,2,0.0,10152,17099,1636,1599,2755,15382,8980,1613,2,55.0,10.0,67
352,116435,Status,1,5,4,3,1.0,23832,42313,1701,1570,2838,37816,21352,1578,6,210.0,39.0,255
362,116091,Status,2,5,5,7,0.0,9232,16811,908,861,1967,12996,7200,843,1,129.0,36.0,166
371,113028,Status,2,4,6,3,1.0,17912,34774,2750,2567,6591,21009,11408,2256,17,447.0,123.0,587
416,104070,Status,1,3,3,15,0.0,9120,14759,951,937,1290,13246,8004,924,3,25.0,6.0,34

In [32]:
merge2 = pd.concat([sub2,sub3])
merge2

,Page total likes,Type,Category,Post Month,Post Weekday,Post Hour,Paid,Lifetime Post Total Reach,Lifetime Post Total Impressions,Lifetime Engaged Users,Lifetime Post Consumers,Lifetime Post Consumptions,Lifetime Post Impressions by people who have liked your Page,Lifetime Post reach by people who like your Page,Lifetime People who have liked your Page and engaged with your post,comment,like,share,Total Interactions
1,139441,Status,2,12,3,10,0.0,10460,19057,1457,1361,1674,11710,6112,1108,5,130.0,29.0,164
5,139441,Status,2,12,1,9,0.0,10472,20849,1191,1073,1389,16034,7852,1016,1,152.0,33.0,186
8,139441,Status,2,12,7,3,0.0,11844,22538,1530,1407,1692,15220,7912,1250,0,161.0,31.0,192
10,139441,Status,2,12,5,10,0.0,21744,42334,4258,4100,4540,37849,18952,3798,0,233.0,19.0,252
15,138414,Status,2,12,3,10,0.0,10060,19680,1264,1209,1425,17272,8548,1162,4,86.0,18.0,108
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,137059,Photo,3,10,6,10,0.0,3090,5744,391,257,360,3521,1796,293,5,153.0,27.0,185
96,137059,Photo,1,10,6,3,0.0,1101,2548,324,287,2418,1284,704,220,3,51.0,11.0,65
97,137059,Photo,2,10,5,11,0.0,2819,5230,318,218,303,3128,1622,240,1,115.0,26.0,142
98,137020,Status,2,10,5,3,1.0,12468,24917,2143,1966,2576,15850,7636,1661,7,310.0,61.0,378
99,137020,Photo,1,10,4,10,0.0,12776,21893,785,539,881,13272,7800,575,12,328.0,90.0,430

In [35]:
merge3 = pd.concat([sub3,sub2],axis=1)
merge3

,Page total likes,Type,Category,Post Month,Post Weekday,Post Hour,Paid,Lifetime Post Total Reach,Lifetime Post Total Impressions,Lifetime Engaged Users,...,Lifetime Engaged Users,Lifetime Post Consumers,Lifetime Post Consumptions,Lifetime Post Impressions by people who have liked your Page,Lifetime Post reach by people who like your Page,Lifetime People who have liked your Page and engaged with your post,comment,like,share,Total Interactions
0,139441.0,Photo,2.0,12.0,4.0,3.0,0.0,2752.0,5091.0,178.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,139441.0,Status,2.0,12.0,3.0,10.0,0.0,10460.0,19057.0,1457.0,...,1457.0,1361.0,1674.0,11710.0,6112.0,1108.0,5.0,130.0,29.0,164.0
2,139441.0,Photo,3.0,12.0,3.0,3.0,0.0,2413.0,4373.0,177.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,139441.0,Photo,2.0,12.0,2.0,10.0,1.0,50128.0,87991.0,2211.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,139441.0,Photo,2.0,12.0,2.0,3.0,0.0,7244.0,13594.0,671.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
334,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1636.0,1599.0,2755.0,15382.0,8980.0,1613.0,2.0,55.0,10.0,67.0
352,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1701.0,1570.0,2838.0,37816.0,21352.0,1578.0,6.0,210.0,39.0,255.0
362,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,908.0,861.0,1967.0,12996.0,7200.0,843.0,1.0,129.0,36.0,166.0
371,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2750.0,2567.0,6591.0,21009.0,11408.0,2256.0,17.0,447.0,123.0,587.0
416,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,951.0,937.0,1290.0,13246.0,8004.0,924.0,3.0,25.0,6.0,34.0

In [36]:
sub3.shape

(100, 19)

In [37]:
sub2.shape

(45, 19)

In [42]:
df.sort_values(by=['Category'])

,Page total likes,Type,Category,Post Month,Post Weekday,Post Hour,Paid,Lifetime Post Total Reach,Lifetime Post Total Impressions,Lifetime Engaged Users,Lifetime Post Consumers,Lifetime Post Consumptions,Lifetime Post Impressions by people who have liked your Page,Lifetime Post reach by people who like your Page,Lifetime People who have liked your Page and engaged with your post,comment,like,share,Total Interactions
128,136393,Photo,1,10,6,13,0.0,645,1117,195,192,224,989,554,166,0,4.0,1.0,5
144,136013,Photo,1,10,2,3,1.0,50736,140432,1462,1450,8308,46252,15552,1275,3,41.0,9.0,53
145,136013,Photo,1,10,1,10,1.0,5324,11040,528,483,861,8627,4054,448,6,76.0,14.0,96
402,107907,Photo,1,4,3,4,1.0,39568,47128,741,652,957,22022,16096,519,4,128.0,17.0,149
401,107907,Photo,1,4,3,13,1.0,46192,80227,1364,1096,1697,32842,16960,762,9,329.0,38.0,376
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
356,116435,Photo,3,5,1,13,0.0,4202,7633,562,481,730,6173,3298,428,3,148.0,16.0,167
359,116091,Photo,3,5,7,2,0.0,6984,12066,780,631,1116,8188,4776,570,25,256.0,54.0,335
361,116091,Photo,3,5,6,3,0.0,3332,5797,463,406,552,4347,2330,341,0,87.0,18.0,105
143,136013,Photo,3,10,2,10,1.0,16776,39549,714,440,720,11860,6200,590,10,377.0,60.0,447
162,135617,Photo,3,9,6,10,0.0,7512,13633,769,614,951,5503,3260,530,22,290.0,98.0,410

In [44]:
df.sort_values(by=['Category'])

,Page total likes,Type,Category,Post Month,Post Weekday,Post Hour,Paid,Lifetime Post Total Reach,Lifetime Post Total Impressions,Lifetime Engaged Users,Lifetime Post Consumers,Lifetime Post Consumptions,Lifetime Post Impressions by people who have liked your Page,Lifetime Post reach by people who like your Page,Lifetime People who have liked your Page and engaged with your post,comment,like,share,Total Interactions
128,136393,Photo,1,10,6,13,0.0,645,1117,195,192,224,989,554,166,0,4.0,1.0,5
144,136013,Photo,1,10,2,3,1.0,50736,140432,1462,1450,8308,46252,15552,1275,3,41.0,9.0,53
145,136013,Photo,1,10,1,10,1.0,5324,11040,528,483,861,8627,4054,448,6,76.0,14.0,96
402,107907,Photo,1,4,3,4,1.0,39568,47128,741,652,957,22022,16096,519,4,128.0,17.0,149
401,107907,Photo,1,4,3,13,1.0,46192,80227,1364,1096,1697,32842,16960,762,9,329.0,38.0,376
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
356,116435,Photo,3,5,1,13,0.0,4202,7633,562,481,730,6173,3298,428,3,148.0,16.0,167
359,116091,Photo,3,5,7,2,0.0,6984,12066,780,631,1116,8188,4776,570,25,256.0,54.0,335
361,116091,Photo,3,5,6,3,0.0,3332,5797,463,406,552,4347,2330,341,0,87.0,18.0,105
143,136013,Photo,3,10,2,10,1.0,16776,39549,714,440,720,11860,6200,590,10,377.0,60.0,447
162,135617,Photo,3,9,6,10,0.0,7512,13633,769,614,951,5503,3260,530,22,290.0,98.0,410

In [45]:
df.sort_values(by=['Type'])

,Page total likes,Type,Category,Post Month,Post Weekday,Post Hour,Paid,Lifetime Post Total Reach,Lifetime Post Total Impressions,Lifetime Engaged Users,Lifetime Post Consumers,Lifetime Post Consumptions,Lifetime Post Impressions by people who have liked your Page,Lifetime Post reach by people who like your Page,Lifetime People who have liked your Page and engaged with your post,comment,like,share,Total Interactions
438,98195,Link,2,3,6,6,0.0,5730,10083,103,71,97,8964,4830,92,2,32.0,15.0,49
470,91437,Link,1,2,3,13,0.0,9356,14986,448,381,505,13919,8460,392,4,114.0,13.0,131
41,138895,Link,1,12,6,3,1.0,18480,28438,517,366,460,12078,6752,319,6,187.0,18.0,211
43,138353,Link,1,12,5,3,1.0,2645,4270,134,109,170,2330,1377,101,7,29.0,10.0,46
45,138353,Link,1,12,4,3,1.0,7968,13023,206,158,223,6734,3492,138,4,57.0,10.0,71
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
71,137893,Video,1,11,5,3,1.0,100768,220447,2101,1735,2331,59658,18880,885,17,449.0,84.0,550
55,138329,Video,1,11,6,2,1.0,16416,31950,459,411,539,21436,9568,363,2,65.0,14.0,81
277,126424,Video,1,6,2,13,0.0,139008,277100,1779,1643,2356,107502,38720,1008,23,204.0,44.0,271
243,130791,Video,1,7,3,11,1.0,21872,40413,3872,3822,7327,24667,12920,2218,18,315.0,76.0,409
74,137893,Video,1,11,3,11,0.0,13544,30235,517,458,667,26622,11760,447,2,99.0,13.0,114

In [47]:
df_copy = pd.DataFrame(df)
df_transposed = df_copy.transpose()
df_transposed

,0,1,2,3,4,5,6,7,8,9,...,490,491,492,493,494,495,496,497,498,499
Page total likes,139441,139441,139441,139441,139441,139441,139441,139441,139441,139441,...,85979,85979,85979,85093,85093,85093,81370,81370,81370,81370
Type,Photo,Status,Photo,Photo,Photo,Status,Photo,Photo,Status,Photo,...,Photo,Photo,Link,Photo,Photo,Photo,Photo,Photo,Photo,Photo
Category,2,2,3,2,2,2,3,3,2,3,...,3,3,1,3,3,3,2,1,3,2
Post Month,12,12,12,12,12,12,12,12,12,12,...,1,1,1,1,1,1,1,1,1,1
Post Weekday,4,3,3,2,2,1,1,7,7,6,...,6,6,5,1,7,7,5,5,4,4
Post Hour,3,10,3,10,3,9,3,9,3,10,...,11,3,11,2,10,2,8,2,11,4
Paid,0.0,0.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Lifetime Post Total Reach,2752,10460,2413,50128,7244,10472,11692,13720,11844,4694,...,5280,6184,45920,8412,5400,4684,3480,3778,4156,4188
Lifetime Post Total Impressions,5091,19057,4373,87991,13594,20849,19479,24137,22538,8668,...,8703,10228,5808,13960,9218,7536,6229,7216,7564,7292
Lifetime Engaged Users,178,1457,177,2211,671,1191,481,537,1530,280,...,951,956,753,1179,810,733,537,625,626,564
Lifetime Post Consumers,109,1361,113,790,410,1073,265,232,1407,183,...,911,901,655,1111,756,708,508,572,574,524
Lifetime Post Consumptions,159,1674,154,1119,580,1389,364,305,1692,250,...,1237,1140,763,1632,1003,985,687,795,832,743
Lifetime Post Impressions by people who have liked your Page,3078,11710,2812,61027,6228,16034,15432,19728,15220,4309,...,5757,6085,15766,8632,5654,4750,3961,4742,4534,3861
Lifetime Post reach by people who like your Page,1640,6112,1503,32048,3200,7852,9328,11056,7912,2324,...,3300,3502,10720,5348,3230,2876,2104,2388,2452,2200
Lifetime People who have liked your Page and engaged with your post,119,1108,132,1386,396,1016,379,422,1250,199,...,431,437,220,699,422,392,301,363,370,316
comment,4,5,0,58,19,1,3,0,0,3,...,1,1,0,17,10,5,0,4,7,0
like,79.0,130.0,66.0,1572.0,325.0,152.0,249.0,325.0,161.0,113.0,...,79.0,105.0,128.0,185.0,125.0,53.0,53.0,93.0,91.0,91.0
share,17.0,29.0,14.0,147.0,49.0,33.0,27.0,14.0,31.0,26.0,...,30.0,46.0,9.0,55.0,41.0,26.0,22.0,18.0,38.0,28.0
Total Interactions,100,164,80,1777,393,186,279,339,192,142,...,110,152,137,257,176,84,75,115,136,119

In [48]:
sub1.shape

(426, 19)

In [ ]:
#reshape
numeric_data = df[['Lifetime Post Total Impressions','Lifetime Engaged Users','Lifetime Post Consumers']].head(6).values
numeric_data.shape

(6, 19)

In [55]:
reshaped_data = numeric_data.reshape(3,6)
reshaped_data.shape

(3, 6)

In [61]:
pivot = pd.pivot_table(
    df,
    values='like',
    index='Type',
    aggfunc='mean'
)

pivot

              like
Type
Link     73.318182
Photo   182.600812
Status  176.711111
Video   231.428571